### ISSUE TITLE
What are the life cycle hooks used for ?

### ISSUE THREAD

**Issue by zak905** [zalando-incubator/kubernetes-on-aws#1261]
I am trying to simplify this configuration as much as possible to adapt it to my project which requires less complexity that Zalando clusters. I was wondering what are you using the life cycle hooks for in the Cloud formation templates? 
```
  AutoscalingLifecycleHook:
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      LifecycleHookName: "kube-node-ready-lifecycle-hook"
      DefaultResult: CONTINUE
      HeartbeatTimeout: '600'
      LifecycleTransition: 'autoscaling:EC2_INSTANCE_LAUNCHING'
    Type: 'AWS::AutoScaling::LifecycleHook'
```
Thanks.
