### ISSUE TITLE
Extend PlatformCredentialsSet with metadata

### ISSUE THREAD

**Issue by alterrebe** [zalando-incubator/kubernetes-on-aws#5026]
### Problem

A K8s Secret created for a PlatformCredentialsSet object doesn't inherit its labels and annotations, in particular the `application` label and `janitor/ttl` annotation. Two immediate consequences:

- Secrets are not cleaned up along with parent PlatformCredentialsSets, as they don't have the Janitor annotation;
- It is impossible to list the PCS-derived secrets per application using `zkubectl get secrets -l application=APP_NAME`.

### Proposal

Add `template/metadata` key into the PlatformCredentialsSet spec:

```yaml
apiVersion: zalando.org/vNNN
kind: PlatformCredentialsSet
metadata:
  ... PCS metadata ...
spec:
  application: APP_NAME
  tokens:
    ...
  clients:
    ...
  template:
    metadata:
      labels:
        application: APP_NAME
      annotations:
        janitor/ttl: 3d
```
